version: '1.0'
stages:
  - prepare
  - test
  - build
  - deploy  
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'robertmaury/react-sample-app'
    revision: master
    git: github
  MyUnitTests:
    title: Unit test
    stage: test
    image: node:8.16
    commands:
      - yarn install
      - yarn test
    environment:
      - CI=true
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: daquinox/react-sample-app
    working_directory: ./
    tag: 'with-nginx'
    dockerfile: Dockerfile
  deploy:
    type: deploy
    description: react-dev
    title: react-dev
    fail_fast: true
    stage: deploy
    arguments:
      kind: kubernetes
      cluster: digitalOcean@codefresh-test
      namespace: default
      service: react-sample-app
      candidate:
        image: daquinox/react-sample-app:with-nginx
        registry: dockerhub
